[package]
name = "dwarf-eye-world"
description = "Decodes DFHack map blocks into a voxel model"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dfhack-remote = { path = "../dfhack-remote" }
dwarf-eye-art = { path = "../dwarf-eye-art" }
